# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lidar_pb2 as lidar__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lidar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LidarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getLidarScan = channel.unary_stream(
                '/sensors.LidarService/getLidarScan',
                request_serializer=lidar__pb2.LidarStreamRequest.SerializeToString,
                response_deserializer=lidar__pb2.PointCloud3.FromString,
                _registered_method=True)
        self.getSubSampledLidarScan = channel.stream_stream(
                '/sensors.LidarService/getSubSampledLidarScan',
                request_serializer=lidar__pb2.SubSampledLidarStreamRequest.SerializeToString,
                response_deserializer=lidar__pb2.PointCloud3.FromString,
                _registered_method=True)


class LidarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getLidarScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getSubSampledLidarScan(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LidarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getLidarScan': grpc.unary_stream_rpc_method_handler(
                    servicer.getLidarScan,
                    request_deserializer=lidar__pb2.LidarStreamRequest.FromString,
                    response_serializer=lidar__pb2.PointCloud3.SerializeToString,
            ),
            'getSubSampledLidarScan': grpc.stream_stream_rpc_method_handler(
                    servicer.getSubSampledLidarScan,
                    request_deserializer=lidar__pb2.SubSampledLidarStreamRequest.FromString,
                    response_serializer=lidar__pb2.PointCloud3.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensors.LidarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sensors.LidarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LidarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getLidarScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sensors.LidarService/getLidarScan',
            lidar__pb2.LidarStreamRequest.SerializeToString,
            lidar__pb2.PointCloud3.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getSubSampledLidarScan(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sensors.LidarService/getSubSampledLidarScan',
            lidar__pb2.SubSampledLidarStreamRequest.SerializeToString,
            lidar__pb2.PointCloud3.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
