# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lidar.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'lidar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0blidar.proto\x12\x07sensors\"\x91\x01\n\x06Point3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0e\n\x01r\x18\x04 \x01(\x02H\x00\x88\x01\x01\x12\x0e\n\x01g\x18\x05 \x01(\x02H\x01\x88\x01\x01\x12\x0e\n\x01\x62\x18\x06 \x01(\x02H\x02\x88\x01\x01\x12\x16\n\tintensity\x18\x07 \x01(\rH\x03\x88\x01\x01\x42\x04\n\x02_rB\x04\n\x02_gB\x04\n\x02_bB\x0c\n\n_intensity\"T\n\x0bPointCloud3\x12\x1f\n\x06points\x18\x01 \x03(\x0b\x32\x0f.sensors.Point3\x12\x16\n\ttimestamp\x18\x02 \x01(\x04H\x00\x88\x01\x01\x42\x0c\n\n_timestamp\"\x14\n\x12LidarStreamRequest\"2\n\x1cSubSampledLidarStreamRequest\x12\x12\n\nvoxel_size\x18\x01 \x01(\x02\x32\xae\x01\n\x0cLidarService\x12\x43\n\x0cgetLidarScan\x12\x1b.sensors.LidarStreamRequest\x1a\x14.sensors.PointCloud30\x01\x12Y\n\x16getSubSampledLidarScan\x12%.sensors.SubSampledLidarStreamRequest\x1a\x14.sensors.PointCloud3(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lidar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT3']._serialized_start=25
  _globals['_POINT3']._serialized_end=170
  _globals['_POINTCLOUD3']._serialized_start=172
  _globals['_POINTCLOUD3']._serialized_end=256
  _globals['_LIDARSTREAMREQUEST']._serialized_start=258
  _globals['_LIDARSTREAMREQUEST']._serialized_end=278
  _globals['_SUBSAMPLEDLIDARSTREAMREQUEST']._serialized_start=280
  _globals['_SUBSAMPLEDLIDARSTREAMREQUEST']._serialized_end=330
  _globals['_LIDARSERVICE']._serialized_start=333
  _globals['_LIDARSERVICE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
