# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lidar_pb2 as lidar__pb2
import slam_pb2 as slam__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in slam_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SlamServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMap = channel.unary_unary(
                '/sensors.SlamService/GetMap',
                request_serializer=slam__pb2.Empty.SerializeToString,
                response_deserializer=lidar__pb2.PointCloud3.FromString,
                _registered_method=True)
        self.GetMapIncrements = channel.unary_stream(
                '/sensors.SlamService/GetMapIncrements',
                request_serializer=slam__pb2.Empty.SerializeToString,
                response_deserializer=lidar__pb2.PointCloud3.FromString,
                _registered_method=True)
        self.GetTransformedScan = channel.unary_stream(
                '/sensors.SlamService/GetTransformedScan',
                request_serializer=slam__pb2.Empty.SerializeToString,
                response_deserializer=lidar__pb2.PointCloud3.FromString,
                _registered_method=True)
        self.GetCorrespondences = channel.unary_stream(
                '/sensors.SlamService/GetCorrespondences',
                request_serializer=slam__pb2.Empty.SerializeToString,
                response_deserializer=lidar__pb2.PointCloud3.FromString,
                _registered_method=True)
        self.GetPose = channel.unary_stream(
                '/sensors.SlamService/GetPose',
                request_serializer=slam__pb2.Empty.SerializeToString,
                response_deserializer=slam__pb2.Pose3D.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/sensors.SlamService/Stop',
                request_serializer=slam__pb2.Empty.SerializeToString,
                response_deserializer=slam__pb2.Empty.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/sensors.SlamService/Start',
                request_serializer=slam__pb2.Empty.SerializeToString,
                response_deserializer=slam__pb2.Empty.FromString,
                _registered_method=True)
        self.Reset = channel.unary_unary(
                '/sensors.SlamService/Reset',
                request_serializer=slam__pb2.Empty.SerializeToString,
                response_deserializer=slam__pb2.Empty.FromString,
                _registered_method=True)


class SlamServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMapIncrements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTransformedScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCorrespondences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SlamServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=slam__pb2.Empty.FromString,
                    response_serializer=lidar__pb2.PointCloud3.SerializeToString,
            ),
            'GetMapIncrements': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMapIncrements,
                    request_deserializer=slam__pb2.Empty.FromString,
                    response_serializer=lidar__pb2.PointCloud3.SerializeToString,
            ),
            'GetTransformedScan': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTransformedScan,
                    request_deserializer=slam__pb2.Empty.FromString,
                    response_serializer=lidar__pb2.PointCloud3.SerializeToString,
            ),
            'GetCorrespondences': grpc.unary_stream_rpc_method_handler(
                    servicer.GetCorrespondences,
                    request_deserializer=slam__pb2.Empty.FromString,
                    response_serializer=lidar__pb2.PointCloud3.SerializeToString,
            ),
            'GetPose': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPose,
                    request_deserializer=slam__pb2.Empty.FromString,
                    response_serializer=slam__pb2.Pose3D.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=slam__pb2.Empty.FromString,
                    response_serializer=slam__pb2.Empty.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=slam__pb2.Empty.FromString,
                    response_serializer=slam__pb2.Empty.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=slam__pb2.Empty.FromString,
                    response_serializer=slam__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sensors.SlamService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sensors.SlamService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SlamService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensors.SlamService/GetMap',
            slam__pb2.Empty.SerializeToString,
            lidar__pb2.PointCloud3.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMapIncrements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sensors.SlamService/GetMapIncrements',
            slam__pb2.Empty.SerializeToString,
            lidar__pb2.PointCloud3.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTransformedScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sensors.SlamService/GetTransformedScan',
            slam__pb2.Empty.SerializeToString,
            lidar__pb2.PointCloud3.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCorrespondences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sensors.SlamService/GetCorrespondences',
            slam__pb2.Empty.SerializeToString,
            lidar__pb2.PointCloud3.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sensors.SlamService/GetPose',
            slam__pb2.Empty.SerializeToString,
            slam__pb2.Pose3D.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensors.SlamService/Stop',
            slam__pb2.Empty.SerializeToString,
            slam__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensors.SlamService/Start',
            slam__pb2.Empty.SerializeToString,
            slam__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sensors.SlamService/Reset',
            slam__pb2.Empty.SerializeToString,
            slam__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
