# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: slam.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'slam.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import lidar_pb2 as lidar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nslam.proto\x12\x07sensors\x1a\x0blidar.proto\"\x07\n\x05\x45mpty\"T\n\x06Pose3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x0b\n\x03phi\x18\x04 \x01(\x01\x12\r\n\x05omega\x18\x05 \x01(\x01\x12\r\n\x05theta\x18\x06 \x01(\x01\x32\xd6\x02\n\x0bSlamService\x12.\n\x06GetMap\x12\x0e.sensors.Empty\x1a\x14.sensors.PointCloud3\x12:\n\x10GetMapIncrements\x12\x0e.sensors.Empty\x1a\x14.sensors.PointCloud30\x01\x12\x31\n\x07GetScan\x12\x0e.sensors.Empty\x1a\x14.sensors.PointCloud30\x01\x12<\n\x12GetTransformedScan\x12\x0e.sensors.Empty\x1a\x14.sensors.PointCloud30\x01\x12<\n\x12GetCorrespondences\x12\x0e.sensors.Empty\x1a\x14.sensors.PointCloud30\x01\x12,\n\x07GetPose\x12\x0e.sensors.Empty\x1a\x0f.sensors.Pose3D0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'slam_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_POSE3D']._serialized_start=45
  _globals['_POSE3D']._serialized_end=129
  _globals['_SLAMSERVICE']._serialized_start=132
  _globals['_SLAMSERVICE']._serialized_end=474
# @@protoc_insertion_point(module_scope)
