# Based on msensor compose file. 

services:

  # 1. The PTP Grandmaster Clock Service (Time sync with sensors)
  ptp-master:
    build:
      context: .
      dockerfile_inline: |
        FROM debian:trixie-slim
        RUN apt-get update && \
            apt-get install -y --no-install-recommends ptpd && \
            rm -rf /var/lib/apt/lists/*
        CMD ["ptpd", "-M", "-i", "eth0", "-C"]
    container_name: livox_ptp_master
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_TIME
    restart: always

  mslam:
    image: mdnf1992/mslam
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    init: true
    restart: unless-stopped

    network_mode: host
    volumes:
      - "./config/:/config"
    command: ["mslam", "-c", "/config/mslam.jsonc"]

  mslam-viewer:
    image: mdnf1992/mslam-viewer
    init: true
    restart: unless-stopped
    network_mode: host
