# Based on msensor compose file. 

services:

  # 1. The PTP Grandmaster Clock Service (Time sync with sensors)
  ptp-master:
    build:
      context: .
      dockerfile_inline: |
        FROM debian:trixie-slim
        RUN apt-get update && \
            apt-get install -y --no-install-recommends ptpd && \
            rm -rf /var/lib/apt/lists/*
        CMD ["ptpd", "-M", "-i", "eth0", "-C"]
    container_name: livox_ptp_master
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_TIME
    restart: always

  msensor:
    image: mdnf1992/msensor
    init: true
    restart: unless-stopped
    pull_policy: always
    privileged: true
    network_mode: host
    command: ["sensor_publisher", "/cfg/publisher_config.json"]
    ports:
      - "50051:50051"
    volumes:
      - "./cfg:/cfg"
      - "/dev:/dev"
      - "/run/udev:/run/udev"

  mslam:
    image: mdnf1992/mslam
    init: true
    restart: unless-stopped
    pull_policy: always
    network_mode: host
    profiles: ["slam"]
    volumes:
      - "./slam.config:/slam.config"
    command: ["mslam", "-c", "/slam.config"]

  mslam-viewer:
    image: mdnf1992/mslam-viewer
    init: true
    restart: unless-stopped
    pull_policy: always
    network_mode: host
    profiles: ["slam"]
